// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package fst.proto;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional sint32 field1 = 1;
    /**
     * <code>optional sint32 field1 = 1;</code>
     */
    boolean hasField1();
    /**
     * <code>optional sint32 field1 = 1;</code>
     */
    int getField1();

    // optional string field2 = 2;
    /**
     * <code>optional string field2 = 2;</code>
     */
    boolean hasField2();
    /**
     * <code>optional string field2 = 2;</code>
     */
    java.lang.String getField2();
    /**
     * <code>optional string field2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getField2Bytes();
  }
  /**
   * Protobuf type {@code fst.proto.TestObject}
   */
  public static final class TestObject extends
      com.google.protobuf.GeneratedMessage
      implements TestObjectOrBuilder {
    // Use TestObject.newBuilder() to construct.
    private TestObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestObject defaultInstance;
    public static TestObject getDefaultInstance() {
      return defaultInstance;
    }

    public TestObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              field1_ = input.readSInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              field2_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fst.proto.Test.internal_static_fst_proto_TestObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fst.proto.Test.internal_static_fst_proto_TestObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fst.proto.Test.TestObject.class, fst.proto.Test.TestObject.Builder.class);
    }

    public static com.google.protobuf.Parser<TestObject> PARSER =
        new com.google.protobuf.AbstractParser<TestObject>() {
      public TestObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional sint32 field1 = 1;
    public static final int FIELD1_FIELD_NUMBER = 1;
    private int field1_;
    /**
     * <code>optional sint32 field1 = 1;</code>
     */
    public boolean hasField1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional sint32 field1 = 1;</code>
     */
    public int getField1() {
      return field1_;
    }

    // optional string field2 = 2;
    public static final int FIELD2_FIELD_NUMBER = 2;
    private java.lang.Object field2_;
    /**
     * <code>optional string field2 = 2;</code>
     */
    public boolean hasField2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string field2 = 2;</code>
     */
    public java.lang.String getField2() {
      java.lang.Object ref = field2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          field2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string field2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getField2Bytes() {
      java.lang.Object ref = field2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      field1_ = 0;
      field2_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, field1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getField2Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, field1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getField2Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fst.proto.Test.TestObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fst.proto.Test.TestObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fst.proto.Test.TestObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fst.proto.Test.TestObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fst.proto.Test.TestObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fst.proto.Test.TestObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fst.proto.Test.TestObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fst.proto.Test.TestObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fst.proto.Test.TestObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fst.proto.Test.TestObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fst.proto.Test.TestObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fst.proto.TestObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fst.proto.Test.TestObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fst.proto.Test.internal_static_fst_proto_TestObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fst.proto.Test.internal_static_fst_proto_TestObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fst.proto.Test.TestObject.class, fst.proto.Test.TestObject.Builder.class);
      }

      // Construct using fst.proto.Test.TestObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        field1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        field2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fst.proto.Test.internal_static_fst_proto_TestObject_descriptor;
      }

      public fst.proto.Test.TestObject getDefaultInstanceForType() {
        return fst.proto.Test.TestObject.getDefaultInstance();
      }

      public fst.proto.Test.TestObject build() {
        fst.proto.Test.TestObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fst.proto.Test.TestObject buildPartial() {
        fst.proto.Test.TestObject result = new fst.proto.Test.TestObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.field1_ = field1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.field2_ = field2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fst.proto.Test.TestObject) {
          return mergeFrom((fst.proto.Test.TestObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fst.proto.Test.TestObject other) {
        if (other == fst.proto.Test.TestObject.getDefaultInstance()) return this;
        if (other.hasField1()) {
          setField1(other.getField1());
        }
        if (other.hasField2()) {
          bitField0_ |= 0x00000002;
          field2_ = other.field2_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fst.proto.Test.TestObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fst.proto.Test.TestObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional sint32 field1 = 1;
      private int field1_ ;
      /**
       * <code>optional sint32 field1 = 1;</code>
       */
      public boolean hasField1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional sint32 field1 = 1;</code>
       */
      public int getField1() {
        return field1_;
      }
      /**
       * <code>optional sint32 field1 = 1;</code>
       */
      public Builder setField1(int value) {
        bitField0_ |= 0x00000001;
        field1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 field1 = 1;</code>
       */
      public Builder clearField1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field1_ = 0;
        onChanged();
        return this;
      }

      // optional string field2 = 2;
      private java.lang.Object field2_ = "";
      /**
       * <code>optional string field2 = 2;</code>
       */
      public boolean hasField2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string field2 = 2;</code>
       */
      public java.lang.String getField2() {
        java.lang.Object ref = field2_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          field2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string field2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getField2Bytes() {
        java.lang.Object ref = field2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          field2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string field2 = 2;</code>
       */
      public Builder setField2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        field2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string field2 = 2;</code>
       */
      public Builder clearField2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        field2_ = getDefaultInstance().getField2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string field2 = 2;</code>
       */
      public Builder setField2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        field2_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fst.proto.TestObject)
    }

    static {
      defaultInstance = new TestObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fst.proto.TestObject)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_fst_proto_TestObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fst_proto_TestObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\tfst.proto\",\n\nTestObject\022\016\n" +
      "\006field1\030\001 \001(\021\022\016\n\006field2\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_fst_proto_TestObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_fst_proto_TestObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_fst_proto_TestObject_descriptor,
              new java.lang.String[] { "Field1", "Field2", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
